# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debeb21034396fa8fdd32ac4b933a2f18d4bd5d3c762ac9b923745fcfb7d7f493cbd9272c22f811155b97ffa2b7be497c1e3008c8dc11c640c6b16e1025b27a7

test:
  secret_key_base: 7d7c73c6364dd56c176025dbe6762b29a7cd541f96edbcb47214917131bfb67cfdfddca8c581732d3b003fcfed24f63f10cdff62d42872057c4559d8bc363418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
